In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Vocabulary size
voc_size=10000

In [6]:
#One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4509, 3441, 1403, 604], [4509, 3441, 1403, 3798], [4509, 4628, 1403, 3308], [5040, 3438, 4154, 2482, 6060], [5040, 3438, 4154, 2482, 6830], [7944, 4509, 1197, 1403, 6781], [7923, 7570, 1333, 2482]]


In [8]:
#Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4509 3441 1403  604]
 [   0    0    0    0 4509 3441 1403 3798]
 [   0    0    0    0 4509 4628 1403 3308]
 [   0    0    0 5040 3438 4154 2482 6060]
 [   0    0    0 5040 3438 4154 2482 6830]
 [   0    0    0 7944 4509 1197 1403 6781]
 [   0    0    0    0 7923 7570 1333 2482]]


In [12]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

[[[ 0.00065156  0.02957343  0.02997332 -0.02637925  0.02609039
    0.00720797  0.04178551  0.01044242 -0.0493057   0.04256633]
  [ 0.00065156  0.02957343  0.02997332 -0.02637925  0.02609039
    0.00720797  0.04178551  0.01044242 -0.0493057   0.04256633]
  [ 0.00065156  0.02957343  0.02997332 -0.02637925  0.02609039
    0.00720797  0.04178551  0.01044242 -0.0493057   0.04256633]
  [ 0.00065156  0.02957343  0.02997332 -0.02637925  0.02609039
    0.00720797  0.04178551  0.01044242 -0.0493057   0.04256633]
  [ 0.0283535   0.01420883  0.03308788  0.01765356 -0.00378184
    0.01956954 -0.03682083 -0.00969122 -0.00589668  0.01192409]
  [-0.01711575 -0.04077976 -0.01726381  0.04748902 -0.01973717
   -0.03525435  0.00498893  0.04194574  0.04265812  0.04020789]
  [ 0.01764822 -0.04575932 -0.00109086 -0.01632231  0.01484715
    0.01918739 -0.02087958 -0.04724246 -0.00364677  0.01159797]
  [ 0.03074378  0.04071881 -0.01559066  0.01613228 -0.02563351
   -0.00675546  0.02895347  0.02152738  0.000540

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 4509, 3441, 1403,  604])

In [17]:
print(model.predict(embedded_docs)[0])

[[ 0.00065156  0.02957343  0.02997332 -0.02637925  0.02609039  0.00720797
   0.04178551  0.01044242 -0.0493057   0.04256633]
 [ 0.00065156  0.02957343  0.02997332 -0.02637925  0.02609039  0.00720797
   0.04178551  0.01044242 -0.0493057   0.04256633]
 [ 0.00065156  0.02957343  0.02997332 -0.02637925  0.02609039  0.00720797
   0.04178551  0.01044242 -0.0493057   0.04256633]
 [ 0.00065156  0.02957343  0.02997332 -0.02637925  0.02609039  0.00720797
   0.04178551  0.01044242 -0.0493057   0.04256633]
 [ 0.0283535   0.01420883  0.03308788  0.01765356 -0.00378184  0.01956954
  -0.03682083 -0.00969122 -0.00589668  0.01192409]
 [-0.01711575 -0.04077976 -0.01726381  0.04748902 -0.01973717 -0.03525435
   0.00498893  0.04194574  0.04265812  0.04020789]
 [ 0.01764822 -0.04575932 -0.00109086 -0.01632231  0.01484715  0.01918739
  -0.02087958 -0.04724246 -0.00364677  0.01159797]
 [ 0.03074378  0.04071881 -0.01559066  0.01613228 -0.02563351 -0.00675546
   0.02895347  0.02152738  0.00054048  0.01959721]]